- name: Ensure unzip is installed (Ubuntu/Debian)
  apt:
    name: unzip
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure unzip is installed (RHEL/CentOS)
  yum:
    name: unzip
    state: present
  when: ansible_os_family == "RedHat"

- name: Create Vault user and group
  user:
    name: "{{ vault_user }}"
    shell: /usr/sbin/nologin
    create_home: no
    system: yes

- name: Download Vault binary
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault.zip"
    mode: '0644'

- name: Unzip Vault binary
  unarchive:
    src: /tmp/vault.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Ensure Vault binary is executable
  file:
    path: /usr/local/bin/vault
    mode: '0755'
